apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zmvt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zmvt
    app.kubernetes.io/part-of: byoc-app-zohn
  name: zmvt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: zmvt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: zmvt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-hrsx-tenant/byoc-app-zohn/zmvt@sha256:4fc335427daa9965c369c3329a5a5dbdc105f312ea1012660e003f55117545e5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
