apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zmvt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zmvt
    app.kubernetes.io/part-of: byoc-app-zohn
  name: zmvt
spec:
  rules:
  - host: zmvt-byoc-hrsx-tenant.apps.dfb0e4d20dff66cc881c.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: zmvt
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
